framework:
    messenger:
        transports:
            async: 'doctrine://default?queue_name=async'
        routing:
            'App\Message\OrderCreatedMessage': async
            'App\Message\OrderStatusChangedMessage': async
